$(document).ready(function(){
	$(".one").mouseenter(function(){
		$(".name-one").toggleClass("hidden");
	})
	$(".two").mouseenter(function(){
		$(".name-two").toggleClass("hidden");
	})
	$(".three").mouseenter(function(){
		$(".name-three").toggleClass("hidden");
	})
	$(".four").mouseenter(function(){
		$(".name-four").toggleClass("hidden");
	})
	$(".five").mouseenter(function(){
		$(".name-five").toggleClass("hidden");
	})
	$(".six").mouseenter(function(){
		$(".name-six").toggleClass("hidden");
	})
	$(".seven").mouseenter(function(){
		$(".name-seven").toggleClass("hidden");
	})
	$(".eight").mouseenter(function(){
		$(".name-eight").toggleClass("hidden");
	})
	$(".nine").mouseenter(function(){
		$(".name-nine").toggleClass("hidden");
	})
	$(".ten").mouseenter(function(){
		$(".name-ten").toggleClass("hidden");
	})
	$(".eleven").mouseenter(function(){
		$(".name-eleven").toggleClass("hidden");
	})
	$(".twelve").mouseenter(function(){
		$(".name-twelve").toggleClass("hidden");
	})
	$(".thirteen").mouseenter(function(){
		$(".name-thirteen").toggleClass("hidden");
	})
	$(".fourteen").mouseenter(function(){
		$(".name-fourteen").toggleClass("hidden");
	})
	$(".fifteen").mouseenter(function(){
		$(".name-fifteen").toggleClass("hidden");
	})
	$(".sixteen").mouseenter(function(){
		$(".name-sixteen").toggleClass("hidden");
	})
})